In [4]:
import numpy as np
print("Imported Sucessfully")

Imported Sucessfully


In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
slice_arr=arr[0:5]

In [8]:
slice_arr

array([0, 1, 2, 3, 4])

In [9]:
slice_arr[:]=99

In [10]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### Indexing 2D Arrays

In [13]:
twod_array=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
twod_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
twod_array[2]

array([ 8,  9, 10, 11])

In [16]:
    twod_array[1,3]

7