In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [4]:

arr *5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [9]:
arr3d = np.arange(0,25).reshape(5,5)
arr3d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
arr3d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [12]:
arr3d.sum(axis=1)

array([ 10,  35,  60,  85, 110])